// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/tahasadough/tahasadough.com/internal/web/components/ui"
)

func aboutSection() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"about\" class=\"container flex flex-col items-center justify-center pt-30 md:flex-col-reverse lg:flex-row\"><div class=\"rounded-2xl border border-muted bg-elevated p-0 overflow-hidden sm:w-7/10 lg:w-full\" style=\"aspect-ratio: 3/4\"><img src=\"/images/taha-sadough.webp\" alt=\"Taha Sadough, Software Engineer\" fetchpriority=\"high\" class=\"size-full object-cover transition-all duration-700 hover:scale-105\" onerror=\"this.style.display='none'\"></div><div class=\"space-y-8 py-10 md:px-10\"><div class=\"flex justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Badge("About").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><h2 class=\"text-center text-2xl text-gray md:text-4xl lg:text-5xl\">I&apos;m a <span class=\"text-on-surface\">Software Engineer</span></h2><p class=\"text-center text-base text-gray\">As a Software Engineer, I specialize in architecting scalable, high-performance systems. I believe in the &apos;right tool for the job&apos; philosophy. I design robust architectures tailored to the specific needs of the product&mdash;ranging from efficient, maintainable Modular Monoliths, to distributed Microservices when extreme scale demands it.</p></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
